logon localtd/dbc,dbc;
database bi_user;

CREATE TABLE DW_Customer(

	CustomerID INTEGER NOT NULL,
	Name VARCHAR(150) NOT NULL,
	BirthDate TIMESTAMP(3),
	Age INTEGER NOT NULL,
	GENDER VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	PHONE VARCHAR(100),
	CONSTRAINT PK_CustomerID PRIMARY KEY (CustomerID),
	CONSTRAINT FK_BirthDate FOREIGN KEY (BirthDate) REFERENCES WITH NO CHECK OPTION DW_DATE("DATE")
);